app = "lalac-sg-p1"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  SITE_NAME = "Lala C"
  SITE_URL = "https://lalac-sg-p1.fly.dev"
  CONTACT_EMAIL = "hello@lalac.sg"
  TAKEDOWN_EMAIL = "takedown@lalac.sg"
  SECURITY_EMAIL = "security@lalac.sg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/robots.txt"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
